spring.application.name=RojiRojgar-backened
spring.datasource.url=jdbc:mysql://localhost:3306/RojiRojgar
spring.datasource.username=root
spring.datasource.password=Krish@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false